FROM oven/bun:1

ARG DB_URL
    
WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bun run db:generate

RUN DB_URL=${DB_URL} bunx turbo build --filter=web...

RUN bun run build

EXPOSE 3000

CMD ["bun", "run", "start:frontend"]